### ISSUE TITLE
Cannot install linshare-cli

### ISSUE THREAD

**Issue by alxgomz** [fred49/linshare-cli#1]
I can't install the cli using pip on my ubuntu system.
It is using python 2.7.6 and producing the following output: 

> INFO: Registering argcomplete support in /etc/ for global activation.
> 
> error: [Errno 2] No such file or directory
> ---
> 
> Cleaning up...
>   Removing temporary dir /tmp/pip_build_root...
> Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/argtoolbox/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-74dplT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/argtoolbox
> Exception information:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
>     requirement_set.install(install_options, global_options, root=options.root_path)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
>     requirement.install(install_options, global_options, _args, *_kwargs)
>   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
>     cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
>   File "/usr/lib/python2.7/dist-packages/pip/util.py", line 715, in call_subprocess
>     % (command_desc, proc.returncode, cwd))
> InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/argtoolbox/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-74dplT-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/argtoolbox

**Comment by fred49** [comment]
hello,
bash-completion is it installed ? Debain or centos ?

**Comment by fred49** [comment]
No news, I think this issue is now useless. I'm closing it.
