### ISSUE TITLE
Centos7 / Redhat8 linshareadmcli utf-8 error

### ISSUE THREAD

**Issue by PhidarkMM** [fred49/linshare-cli#10]
Hello,

We are trying to change our mail logo and linshareadmcli returns an utf-8 error (tests on centos 7 and redhat 8 environments) with https://github.com/linagora/linshare/blob/master/documentation/EN/administration/how-to-use-mail-attachment.md

No error on test call:
\# linshareadmcli -v -u root@localhost.localdomain -P "xxx" --auth-type plain-b64 --no-cell -H linshare-admin.xx.yy.zz test
Test
Configuration of linshare-admin-cli :

        Section SERVER
         - host : linshare-admin.xx.yy.zz
         - api_version : 2.2
         - user : root@localhost.localdomain
         - password : xxxxxxxx
         - auth_type : plain
         - base_url : None
         - verify : True
         - nocache : False
         - verbose : None
         - debug : 0

Namespace(__func__=<linsharecli.admin.core.TestCommand object at 0x7f6c3cc1f9e8>, ask_password=False, auth_type='plain-b64', base_url=None, config_file=None, debug=0, debugger_names=None, env_password=False, files=[], host='linshare-admin.xx.yy.zz', no_cell=True, nocache=False, password='xxx', password_from_env=None, server_section=None, user='root@localhost.localdomain', verbose=True, verify=True)
14:30:11 INFO    : End of test command.

\# linshareadmcli -v -u root@localhost.localdomain -P "xxx" --auth-type plain-b64 --no-cell -H linshare-admin.xx.yy.zz mail_configs list

API VERSION: 2.2 (See env variable LS_API).

14:30:35 ERROR   : ValueError : 'utf-8' codec can't decode byte 0x81 in position 1: invalid start byte

Best regards,

**Comment by PhidarkMM** [comment]
Finaly found the correct syntax in DEBUG mode:
export _ARC_DEBUG=1
export _LINSHARE_CLI_USER_DEBUG=True
export LS_DEBUG=3

linshareadmcli -v -u root@localhost.localdomain -P "xxx" --no-verify --auth-type plain -H http://linshare-admin.xx.yy.zz mail_configs list
+---------------------+--------------------------------------+--------------------+----------+---------+---------------------+---------------------+
| name                | uuid                                 | domain             | readonly | visible | creationDate        | modificationDate    |
+---------------------+--------------------------------------+--------------------+----------+---------+---------------------+---------------------+
| Default mail config | 946b190d-4c95-485f-bfe6-d288a2de1edd | LinShareRootDomain | True     | True    | 2022-09-20 13:29:08 | 2022-09-20 13:29:08 |
| MYDOMAIN                 | 37df9e19-0dcf-4d09-bb1d-090314a4ddf3 | LinShareRootDomain | False    | True    | 2022-09-26 13:53:05 | 2022-09-26 13:53:29 |
+---------------------+--------------------------------------+--------------------+----------+---------+---------------------+---------------------+

**Comment by FLeroyAliasNT** [comment]
I found to root cause of the issue "name 'CreateAction' is not defined", in the script '/usr/local/lib/python3.6/site-packages/linsharecli/admin/mail_attachments.py', replace the word 'CreateAction' by 'CreateOneAction' in 'CreateOneAction' class at the beginning of the script.

**Comment by fred49** [comment]
Feel free to contribute, it's Open Source  ;)
